### ISSUE TITLE
Error with Stylus and A-la-carte

### ISSUE THREAD

**Issue by maurop123** [vuetifyjs/vue-cli-plugin-vuetify#1]
Hello, I have problem when using a-la-carte way in vue-cli 3
```
import Vuetify from 'vuetify/es5/components/Vuetify'
import VList from 'vuetify/es5/components/VList'
import VMenu from 'vuetify/es5/components/VMenu'
```

then got this error
```
    /home/wildan/Projects/Sensorfied/EDI/edi-ui/node_modules/vuetify/src/stylus/components/_lists.styl:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){@import '../bootstrap'
                                                                                             ^

    SyntaxError: Invalid or unexpected token

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:316:17)
      at Object.<anonymous> (node_modules/vuetify/es5/components/VList/VList.js:7:1)
      at Object.<anonymous> (node_modules/vuetify/es5/components/VList/index.js:10:14)
```

I was sure when vue create I choose Stylus as the pre-processsor :thinking:
Any suggestion/workaround for this?

**Comment by renoirb** [comment]
I could get something to bypass Stylus transforms and don't get Jest tests.
Assuming one would NOT BE TESTING Stylus generated output, that would be a possible solution.

To my current understanding (I may be wrong); Jest can't run tests on generated CSS.
(Maybe via RegExes?)

The only other reason we'd want to have tests also do Stylus/Less/Sass CSS transformation is to make sure the component build.
But I imagine we would know from another process is something is broken.

[Jest documentation mentions](https://facebook.github.io/jest/docs/en/webpack.html#mocking-css-modules) you can mock transformations. 

At first, I ignored it because it was talking about W3C’s CSS Module (this is separate beast) and I thought it was only for that purpose. Not simple CSS Preprocessor handling.

Then after re-reading, I realised the documentation provided a way to selectively NOT do transformation for CSS.

Since it's breaking tests, and is possibly not needed to have transpiled CSS when it is likely just not used in tests, why not just skiping this step altogether.

I imagine we would have something else to test how CSS is rendered.

**Comment by nekosaur** [comment]
Closing due to inactivity

**Comment by rnenjoy** [comment]
Having this issue aswell with ala carte

**Comment by ekoeryanto** [comment]
I have this issue with vuepress, everything fine if i don't use `v-menu`

**Comment by jacekkarczmarczyk** [comment]
Please provide reproduction steps

**Comment by ekoeryanto** [comment]
@jacekkarczmarczyk mine is not `vue-cli-plugin-vuetify` related issue, but if you want me to create repo with the issue, I'll create it.

**Comment by jacekkarczmarczyk** [comment]
Ok, but create the issue in a proper repo, this one is only for cli3 plugin issues

**Comment by ekoeryanto** [comment]
I am still investigating where the issue come from.

**Comment by Codefa** [comment]
Found a fix go to **node_modules/vuetify/src/stylus/components** there open `_app.styl`
remove the line no:1 
`@import '../bootstrap'`

**Comment by SujanKumarK** [comment]
add following code in babel.config.js.

  plugins: [
    ['transform-imports', {
      'vuetify': {
        'transform': 'vuetify/es5/components/${member}', // eslint-disable-line no-template-curly-in-string
        'preventFullImport': true
      }
    }]
} 

by default vue-cli3 will create this code for us.

we have to add "babel-plugin-transform-imports" dependency

**Comment by desprit** [comment]
Adding `styleMock` into `moduleNameMapper` worked for me:

https://jestjs.io/docs/en/webpack#handling-static-assets
```
// jest.config.js
"\\.(css|less)$": "<rootDir>/assets/css/styleMock.js"
```
```
// assets/css/styleMock.js
module.exports = {};
```
