### ISSUE TITLE
[Bug Report] Vuetify and Sass loader problems

### ISSUE THREAD

**Issue by MrStonkus** [vuetifyjs/vue-cli-plugin-vuetify#114]
### Environment
**Vuetify Version:** 2.0.19

**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
In existing project.

Run: vue add vuetify
Default (recommended)

Log after install:
------------------------------------------------

+ vue-cli-plugin-vuetify@0.6.3
removed 2 packages, updated 1 package and audited 24955 packages in 9.949s
found 0 vulnerabilities

✔  Successfully installed plugin: vue-cli-plugin-vuetify

? Choose a preset: Default (recommended)
 WARN  conflicting versions for project dependency "sass-loader":

- ^8.0.0 injected by generator "undefined"
- ^7.1.0 injected by generator "vue-cli-plugin-vuetify"

Using newer version (^8.0.0), but this may cause build errors.

�🚀  Invoking generator for vue-cli-plugin-vuetify...
�📦  Installing additional dependencies...

added 3 packages from 2 contributors, removed 2 packages and audited 27110 packages in 13.987s
found 0 vulnerabilities

⚓  Running completion hooks...

✔  Successfully invoked generator for plugin: vue-cli-plugin-vuetify
   The following files have been updated / added:

     src/plugins/vuetify.js
     package-lock.json
     package.json
     public/index.html
     src/App.vue
     src/main.js
     src/views/Home.vue

   You should review these changes with git diff and commit them.
-------------------------------------------------------------

Run npm run serve
Log
------------------------------
error  in ./node_modules/vuetify/src/components/VTextarea/VTextarea.sass

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'indentedSyntax'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (C:\Projektai\sales-manager\node_modules\sass-loader\node_modules\schema-utils\dist\validate.js:49:11)
    at Object.loader (C:\Projektai\sales-manager\node_modules\sass-loader\dist\index.js:36:28)

 @ ./node_modules/vuetify/src/components/VTextarea/VTextarea.sass 4:14-205 14:3-18:5 15:22-213
 @ ./node_modules/vuetify/lib/components/VTextarea/VTextarea.js
 @ ./node_modules/vuetify/lib/components/VTextarea/index.js
 @ ./node_modules/vuetify/lib/components/index.js
 @ ./node_modules/vuetify/lib/index.js
 @ ./src/plugins/vuetify.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.0.104:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./node_modules/vuetify/src/components/VSheet/VSheet.sass

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'indentedSyntax'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (C:\Projektai\sales-manager\node_modules\sass-loader\node_modules\schema-utils\dist\validate.js:49:11)
    at Object.loader (C:\Projektai\sales-manager\node_modules\sass-loader\dist\index.js:36:28)

 @ ./node_modules/vuetify/src/components/VSheet/VSheet.sass 4:14-202 14:3-18:5 15:22-210
 @ ./node_modules/vuetify/lib/components/VSheet/VSheet.js
 @ ./node_modules/vuetify/lib/components/VToolbar/VToolbar.js
 @ ./node_modules/vuetify/lib/components/VToolbar/index.js
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.0.104:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 

And a lot of similar errors...

-----------------------------------------------

### Expected Behavior
Succefuly build

### Actual Behavior
A lot of errors

### Reproduction Link
<a href="" target="_blank"></a>

### Other comments
As you can see, there is a lot of errors. I tryed to lover sass-loader versions, and a lot of other things, nothing helped. Waiting for your answer.
Thank you in advance.

**Comment by MrStonkus** [comment]
Finaly I fixed it.
I lovered version of sass-loader from 8.0.0 to 7.1.0 and it worked!
Actualy I was need restore these files after that:
main.js
App.vue
and checked for Vuetify integration, all looks fine.

P.S. With version sass-loader 7.0.0 Vuetify not worked for me.
