### ISSUE TITLE
ERROR  Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.

### ISSUE THREAD

**Issue by atipico** [vuetifyjs/vue-cli-plugin-vuetify#140]
I am trying to install Vuetify and I got this:

vue add vuetify

📦  Installing vue-cli-plugin-vuetify...

+ vue-cli-plugin-vuetify@2.0.2
updated 1 package and audited 14182 packages in 7.936s

12 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

✔  Successfully installed plugin: vue-cli-plugin-vuetify

? Choose a preset: Default (recommended)

🚀  Invoking generator for vue-cli-plugin-vuetify...
 ERROR  Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.
Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.
    at Collection.get (/usr/lib/node_modules/@vue/cli/node_modules/jscodeshift/src/Collection.js:215:13)
    at injectOptions (/usr/lib/node_modules/@vue/cli/lib/util/codemods/injectOptions.js:15:6)
    at newTransform (/usr/lib/node_modules/@vue/cli/node_modules/vue-jscodeshift-adapter/src/jscodeshift-mode.js:9:14)
    at runCodemod (/usr/lib/node_modules/@vue/cli/lib/util/runCodemod.js:29:26)
    at /usr/lib/node_modules/@vue/cli/lib/Generator.js:283:23
    at Array.forEach (<anonymous>)
    at Generator.resolveFiles (/usr/lib/node_modules/@vue/cli/lib/Generator.js:269:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Generator.generate (/usr/lib/node_modules/@vue/cli/lib/Generator.js:168:5)
    at async runGenerator (/usr/lib/node_modules/@vue/cli/lib/invoke.js:120:3)

**Comment by johnleider** [comment]
Need more information. I cannot reproduce this off of a fresh install with @vue/cli@4.1.1

**Comment by mcorning** [comment]
I hit this error just now. i'm using v4.1.1, too. my goal today was to augment an existing vue app that uses vues-orm-localforage. I called `vue add Vuetify` in the project folder. I will try again. tell me what other intel you might need from me.

**Comment by mcorning** [comment]
failed again. here's the console spew:
mcorn@DESKTOP-55SQIHT MINGW64 ~/Documents/GitHub/vue/vuex-orm-localforage-exemples-master (master)
$ vue add vuetify
 WARN  There are uncommited changes in the current repository, it's recommended to commit or stash them first.
? Still proceed? Yes

�📦  Installing vue-cli-plugin-vuetify...

yarn add v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ vue-cli-plugin-vuetify@2.0.5
info All dependencies
└─ vue-cli-plugin-vuetify@2.0.5
Done in 9.99s.
✔  Successfully installed plugin: vue-cli-plugin-vuetify

? Choose a preset: Default (recommended)

�🚀  Invoking generator for vue-cli-plugin-vuetify...
 ERROR  Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.
Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.
    at Collection.get (C:\Users\mcorn\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\jscodeshift\src\Collection.js:215:13)
    at injectOptions (C:\Users\mcorn\AppData\Roaming\npm\node_modules\@vue\cli\lib\util\codemods\injectOptions.js:15:6)
    at newTransform (C:\Users\mcorn\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\vue-jscodeshift-adapter\src\jscodeshift-mode.js:9:14)
    at runCodemod (C:\Users\mcorn\AppData\Roaming\npm\node_modules\@vue\cli\lib\util\runCodemod.js:29:26)
    at Object.keys.forEach.file (C:\Users\mcorn\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:283:23)
    at Array.forEach (<anonymous>)
    at Generator.resolveFiles (C:\Users\mcorn\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:269:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)

$

**Comment by mcorning** [comment]
here is the new line in package.json:
    "vue-cli-plugin-vuetify": "^2.0.5",

**Comment by mcorning** [comment]
and here is the new content in yarn.lock:
"@babel/code-frame@^7.8.3":
  version "7.8.3"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.8.3.tgz#33e25903d7481181534e12ec0a25f16b6fcf419e"
  integrity sha512-a9gxpmdXtZEInkCSHUJDLHZVBgb1QS0jhss4cPP93EW7s+uC5bikET2twEF3KV+7rDblJcmNvTR7VJejqd2C2g==
  dependencies:
    "@babel/highlight" "^7.8.3"

**Comment by paolog22** [comment]
currently experiencing this

**Comment by flaviotsales** [comment]
Solved my issue by
- creating a vue instance `new Vue({options})` on the entrypoint file, which is specified on the "main" key at package.json.
- creating a public/index.html file.

**Comment by paolog22** [comment]
![image](https://user-images.githubusercontent.com/12680745/76680475-b1237180-6623-11ea-8b39-5154be40023a.png)
someone help me with this ?

**Comment by ferdinandfrank** [comment]
@paolog22 I can confirm that this issue is probably caused by modifying the entrypoint file or by deleting the `public/index.html` file before running the command. At least my issue was solved when recreating the original files and running the command again, like @flaviotsales wrote.

**Comment by Takahana** [comment]
I got the same error in my environment trying vue 3.0 with vue-next. In my case, I was able to trick the CLI by writing `new Vue(...)` in `main.ts` to trick the CLI.

**main.ts**
```
createApp(App)
  .use(router)
  .use(store)
  .mount("#app");

// I don't use it by default.
new Vue({
  router,
  store,
  vuetify,
  render: h => h(App)
}).$mount("#app");
```

**Comment by wlafrance** [comment]
Similar issue.  I had an existing vue.js project.
I used vue add typescript to add typescript support.
I then used vue add vuetify 
With these options...
Installing vue-cli-plugin-vuetify...

+ vue-cli-plugin-vuetify@2.0.6
updated 1 package and audited 1624 packages in 8.283s

58 packages are looking for funding
  run `npm fund` for details

found 1069 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
✔  Successfully installed plugin: vue-cli-plugin-vuetify

? Choose a preset: Configure (advanced)
? Use a pre-made template? (will replace App.vue and HelloWorld.vue) No
? Use custom theme? Yes
? Use custom properties (CSS variables)? Yes
? Select icon font Material Design Icons
? Use fonts as a dependency (for Electron or offline)? Yes
? Use a-la-carte components? Yes
? Select locale English

🚀  Invoking generator for vue-cli-plugin-vuetify...
 **ERROR  Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists**.
Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.
    at Collection.get (C:\Users\lafrance.warren\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\jscodeshift\src\Collection.js:213:13)
    at injectOptions (C:\Users\lafrance.warren\AppData\Roaming\npm\node_modules\@vue\cli\lib\util\codemods\injectOptions.js:15:6)
    at newTransform (C:\Users\lafrance.warren\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\vue-jscodeshift-adapter\src\jscodeshift-mode.js:9:14)
    at runCodemod (C:\Users\lafrance.warren\AppData\Roaming\npm\node_modules\@vue\cli\lib\util\runCodemod.js:29:26)
    at Object.keys.forEach.file (C:\Users\lafrance.warren\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:290:23)
    at Array.forEach (<anonymous>)
    at Generator.resolveFiles (C:\Users\lafrance.warren\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:276:24)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
PS D:\vue-component-lib-starter-master>

**Comment by radimhornicek** [comment]
Also confirm, that it was caused by editing public/index.html or src/App.vue and it's component. Thx for help

**Comment by EmmyMay** [comment]
I am using vue 3 with vue-next and I too am running into this error.

**Comment by do-web** [comment]
Same problem, any updates here?


```
Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.
    at Collection.get (/usr/local/lib/node_modules/@vue/cli/node_modules/jscodeshift/src/Collection.js:213:13)
    at injectOptions (/usr/local/lib/node_modules/@vue/cli/lib/util/codemods/injectOptions.js:15:6)
    at newTransform (/usr/local/lib/node_modules/@vue/cli/node_modules/vue-jscodeshift-adapter/src/jscodeshift-mode.js:9:14)
    at runCodemod (/usr/local/lib/node_modules/@vue/cli/lib/util/runCodemod.js:29:26)
    at /usr/local/lib/node_modules/@vue/cli/lib/Generator.js:290:23
    at Array.forEach (<anonymous>)
    at Generator.resolveFiles (/usr/local/lib/node_modules/@vue/cli/lib/Generator.js:276:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Generator.generate (/usr/local/lib/node_modules/@vue/cli/lib/Generator.js:175:5)
    at async runGenerator (/usr/local/lib/node_modules/@vue/cli/lib/invoke.js:111:3)
```

**Comment by EmmyMay** [comment]
> Same problem, any updates here?
> 
> ```
> Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.
>     at Collection.get (/usr/local/lib/node_modules/@vue/cli/node_modules/jscodeshift/src/Collection.js:213:13)
>     at injectOptions (/usr/local/lib/node_modules/@vue/cli/lib/util/codemods/injectOptions.js:15:6)
>     at newTransform (/usr/local/lib/node_modules/@vue/cli/node_modules/vue-jscodeshift-adapter/src/jscodeshift-mode.js:9:14)
>     at runCodemod (/usr/local/lib/node_modules/@vue/cli/lib/util/runCodemod.js:29:26)
>     at /usr/local/lib/node_modules/@vue/cli/lib/Generator.js:290:23
>     at Array.forEach (<anonymous>)
>     at Generator.resolveFiles (/usr/local/lib/node_modules/@vue/cli/lib/Generator.js:276:24)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at async Generator.generate (/usr/local/lib/node_modules/@vue/cli/lib/Generator.js:175:5)
>     at async runGenerator (/usr/local/lib/node_modules/@vue/cli/lib/invoke.js:111:3)
> ```

Are you trying to install vuetify on vue 3?

**Comment by andersonfernandes** [comment]
I'm having the same issue trying to install vue-cli-plugin-vuetify 2.0.7 on vue 2.6.11. 
Does anyone have updates about?

**Comment by EmmyMay** [comment]
> I'm having the same issue trying to install `vue-cli-plugin-vuetify@2.0.7` on `vue@2.6.11`.
> Does anyone have updates about?

I don't think you'll run into this issue if you use vue-cli and do something like 'vue add vuetify'

**Comment by Davejs136** [comment]
I think that this is because vue3 beta has that error! I had to change my main.js. I was trying to install vuex

**Comment by do-web** [comment]
i could solve my problem, there must be the following code in the main.js, otherwise the error will occur. So just add this code before installation:
```
new Vue({
    render: h => h(App),
}).$mount('#app');
```

**Comment by sense-it-gmbh** [comment]
The solution of @do-web works fine. Afterwards I removed the 

```javascript
new Vue({
  vuetify,
  render: h => h(App)
}).$mount('#app')
```
from my `main.js` and added the `.use(vuetify)` to 

```javascript
createApp(App)
  .use(store)
  .use(router)
  .mount('#app')
```

**BTW** It is not sufficient to leave the piece of code there but commented out, it needs to be real code and not a comment! (Would have been nice)

**Comment by anthonygore** [comment]
I'm pretty sure the most recent problems are nothing to do with the vuetify plugin. Seem like most people are coming across this with Vue CLI 4 and vue-next. Should probably move the discussion here https://github.com/vuejs/vue-cli-plugin-vue-next

**Comment by swapneshkumar** [comment]
add following code in main.js

new Vue({
    vuetify,
    render: h => h(App)
}).$mount('#app');

**Comment by mohamedAhmed00** [comment]
any update in this issues , i try all the above solution but not work with me , 


- ^9.0.3 injected by generator "undefined"
- ^8.0.0 injected by generator "vue-cli-plugin-vuetify"

Using newer version (^9.0.3), but this may cause build errors.
 ERROR  Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.
Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.
    at Collection.get (/usr/local/share/.config/yarn/global/node_modules/jscodeshift/src/Collection.js:213:13)
    at injectOptions (/usr/local/share/.config/yarn/global/node_modules/@vue/cli/lib/util/codemods/injectOptions.js:15:6)
    at runTransformation (/usr/local/share/.config/yarn/global/node_modules/vue-codemod/dist/src/run-transformation.js:61:17)
    at /usr/local/share/.config/yarn/global/node_modules/@vue/cli/lib/Generator.js:290:23
    at Array.forEach (<anonymous>)
    at Generator.resolveFiles (/usr/local/share/.config/yarn/global/node_modules/@vue/cli/lib/Generator.js:276:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Generator.generate (/usr/local/share/.config/yarn/global/node_modules/@vue/cli/lib/Generator.js:175:5)
    at async runGenerator (/usr/local/share/.config/yarn/global/node_modules/@vue/cli/lib/invoke.js:111:3)
    at async invoke (/usr/local/share/.config/yarn/global/node_modules/@vue/cli/lib/invoke.js:92:3)

**Comment by wcabezas** [comment]
I confirm that @do-web  solution works for this problem.

**Comment by e3-naibu** [comment]
Hello,
Just learnt about Vuetify and I'm having the same error. I don't see how @do-web solution fixes any thing as @sense-it-gmbh said, I can't start the server. I have tried to install it via the cli and the ui... just in case... @johnleider : any update since Dec 2019?

Any other idea?

This is my environment (fresh install): ... ae error as everyone else.
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 84.0.4147.135
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @ant-design-vue/babel-helper-vue-transform-on:  1.0.1
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.5.4
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.5.4
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.4
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.4
    @vue/cli-plugin-router: ^4.5.4 => 4.5.4
    @vue/cli-plugin-vuex: ^4.5.4 => 4.5.4
    @vue/cli-service: ~4.5.0 => 4.5.4
    @vue/cli-shared-utils:  4.5.4
    @vue/compiler-core:  3.0.0-rc.6
    @vue/compiler-dom:  3.0.0-rc.6
    @vue/compiler-sfc: ^3.0.0-0 => 3.0.0-rc.6
    @vue/compiler-ssr:  3.0.0-rc.6
    @vue/component-compiler-utils:  3.2.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/reactivity:  3.0.0-rc.6
    @vue/runtime-core:  3.0.0-rc.6
    @vue/runtime-dom:  3.0.0-rc.6
    @vue/shared:  3.0.0-rc.6
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^7.0.0-0 => 7.0.0-beta.2
    vue: ^3.0.0-0 => 3.0.0-rc.6
    vue-cli-plugin-vuetify: ~2.0.7 => 2.0.7
    vue-eslint-parser:  7.1.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.3 (16.0.0-beta.5)
    vue-router: ^4.0.0-0 => 4.0.0-beta.7
    vue-style-loader:  4.1.2
    vue-template-es2015-compiler:  1.9.1
    vuetify-loader: ^1.3.0 => 1.6.0
    vuex: ^4.0.0-0 => 4.0.0-beta.4
  npmGlobalPackages:
    @vue/cli: Not Found

**Comment by brule2194** [comment]
please, some one can help me, Im using vue cli 4.5.4 and I have so many problems to install veautify and the bootstrap plugins.

**Comment by brule2194** [comment]
�  Invoking generator for vue-cli-plugin-vuetify...
 ERROR  Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.
Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.
    at Collection.get (C:\Users\Brule\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\jscodeshift\src\Collection.js:213:13)
    at injectOptions (C:\Users\Brule\AppData\Roaming\npm\node_modules\@vue\cli\lib\util\codemods\injectOptions.js:15:6)
    at runTransformation (C:\Users\Brule\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\vue-codemod\dist\src\run-transformation.js:61:17)
    at C:\Users\Brule\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:290:23
    at Array.forEach (<anonymous>)
    at Generator.resolveFiles (C:\Users\Brule\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:276:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Generator.generate (C:\Users\Brule\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:175:5)
    at async runGenerator (C:\Users\Brule\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:111:3)
    at async invoke (C:\Users\Brule\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:92:3)

**Comment by abdullahyaqoob** [comment]
vue3 is giving this error because vue3 is in beta version if you use vue2 you solve your problem. My error is solved by this solution.

**Comment by joshuadabejero** [comment]
I just wanna help on how I fixed. I'm using .js not .ts and I'm not sure if the code is the same but I guess the logic might be. So here's how I solve it.

This is the default auto generated file run by the ```vue create { app name}``` command.
![image](https://user-images.githubusercontent.com/29270980/93203576-3cbebc00-f787-11ea-9e65-70072bd97335.png)

This is how I modified it.
![image](https://user-images.githubusercontent.com/29270980/93203649-5bbd4e00-f787-11ea-8e29-404ff22da961.png)

Vuetify was installed successfully.
![image](https://user-images.githubusercontent.com/29270980/93203697-71cb0e80-f787-11ea-9f3d-2ecd4dd8ea62.png)

Hope it helps! 😄

**Comment by abdullahyaqoob** [comment]
Thanks

**Comment by YusufISMAILOGLU** [comment]
I faced the same error when adding `i18n` to my vue3 app and the solution of @do-web works fine.

**Comment by OgunniyiOwamamwen** [comment]
If you want to used 'Vue-3 + Vuetify' exclude TypeScript Later you can include when you finished initializing and added 'vue add vuetify'.


[![enter image description here][1]][1]


  [1]: https://i.stack.imgur.com/iyZ0A.png

**Comment by rayfoss** [comment]
@OgunniyiOwamamwen your method does not fix the "No matching rule for vue-loader found"

Which is good news... as that means Typescript isn't the incompatible issue here.

**Comment by hardikhari96** [comment]
this is not proper solution, still getting errors

**Comment by imfaruk** [comment]
Just hit the same issue

**Comment by jacekkarczmarczyk** [comment]
Vuetify 2.x doesn't work with Vue 3

https://vuetifyjs.com/en/introduction/roadmap/
