### ISSUE TITLE
Unresolved module error when using a pre-made template

### ISSUE THREAD

**Issue by souserge** [vuetifyjs/vue-cli-plugin-vuetify#32]
I decided to add Vuetify to my newly scaffolded project (using `vue init webpack`), but ran into an error. Here's the full output:
```
$ vue add vuetify

📦  Installing vue-cli-plugin-vuetify...

+ vue-cli-plugin-vuetify@0.1.6
updated 1 package and audited 33078 packages in 21.679s
found 0 vulnerabilities

✔  Successfully installed plugin: vue-cli-plugin-vuetify

? Use a pre-made template? (will replace App.vue and HelloWorld.vue) Yes
? Use custom theme? No
? Use a-la-carte components? Yes
? Use babel/polyfill? No

🚀  Invoking generator for vue-cli-plugin-vuetify...
 ERROR  Error: Cannot find module '@vue/cli-service/generator/template/src/components/HelloWorld.vue' from '.../node_modules/vue-cli-plugin-vuetify/generator/templates/hw/src/components'
Error: Cannot find module '@vue/cli-service/generator/template/src/components/HelloWorld.vue' from '.../node_modules/vue-cli-plugin-vuetify/generator/templates/hw/src/components'
    at Function.module.exports [as sync] (/usr/local/lib/node_modules/@vue/cli/node_modules/resolve/lib/sync.js:43:15)
    at renderFile (/usr/local/lib/node_modules/@vue/cli/lib/GeneratorAPI.js:321:17)
    at _injectFileMiddleware (/usr/local/lib/node_modules/@vue/cli/lib/GeneratorAPI.js:183:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

The problem does not arise when I don't add the pre-made template.

**Comment by jacekkarczmarczyk** [comment]
I'm not sure if vue-cli 3 plays well with `vue init webpack`, you probably need to create your project with `vue create project-name`

**Comment by amritk** [comment]
This still seems to be an issue
```
➜  pulls vue create v


Vue CLI v3.0.4
? Please pick a preset: Manually select features
? Check the features needed for your project: Babel, TS, PWA, CSS Pre-processors, Linter, Unit, E2E
? Use class-style component syntax? Yes
? Use Babel alongside TypeScript for auto-detected polyfills? Yes
? Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default): Stylus
? Pick a linter / formatter config: TSLint
? Pick additional lint features: Lint on save
? Pick a unit testing solution: Jest
? Pick a E2E testing solution: Cypress
? Where do you prefer placing config for Babel, PostCSS, ESLint, etc.? In package.json
? Save this as a preset for future projects? Yes
? Save preset as: plugin


Vue CLI v3.0.4
✨  Creating project in /home/amritk/apps/pulls/v.
🗃  Initializing git repository...
⚙  Installing CLI plugins. This might take a while...

yarn install v1.10.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...

success Saved lockfile.
Done in 8.01s.
🚀  Invoking generators...
📦  Installing additional dependencies...

yarn install v1.10.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Saved lockfile.
Done in 3.76s.
⚓  Running completion hooks...

📄  Generating README.md...

🎉  Successfully created project v.
👉  Get started with the following commands:

 $ cd v
 $ yarn serve

➜  pulls vue add vuetify

📦  Installing vue-cli-plugin-vuetify...

yarn add v1.10.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Saved 1 new dependency.
info Direct dependencies
└─ vue-cli-plugin-vuetify@0.2.0
info All dependencies
└─ vue-cli-plugin-vuetify@0.2.0
Done in 0.25s.
✔  Successfully installed plugin: vue-cli-plugin-vuetify

? Use a pre-made template? (will replace App.vue and HelloWorld.vue) Yes
? Use custom theme? No
? Use custom properties (CSS variables)? No
? Select icon font md
? Use fonts as a dependency (for Electron or offline)? No
? Use a-la-carte components? Yes
? Use babel/polyfill? Yes
? Select locale en

🚀  Invoking generator for vue-cli-plugin-vuetify...
 ERROR  Error: Cannot find module '@vue/cli-service/generator/template/src/components/HelloWorld.vue' from '/home/amritk/apps/pulls/node_modules/vue-cli-plugin-vuetify/generator/templates/hw/src/components'
Error: Cannot find module '@vue/cli-service/generator/template/src/components/HelloWorld.vue' from '/home/amritk/apps/pulls/node_modules/vue-cli-plugin-vuetify/generator/templates/hw/src/components'
    at Function.module.exports [as sync] (/home/amritk/.config/yarn/global/node_modules/resolve/lib/sync.js:43:15)
    at renderFile (/home/amritk/.config/yarn/global/node_modules/@vue/cli/lib/GeneratorAPI.js:322:17)
    at _injectFileMiddleware (/home/amritk/.config/yarn/global/node_modules/@vue/cli/lib/GeneratorAPI.js:184:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
