### ISSUE TITLE
Module build failure after adding plugin (Stylus related?)

### ISSUE THREAD

**Issue by salvadornico** [vuetifyjs/vue-cli-plugin-vuetify#57]
I was setting up a new project from a template repo I've been using for the past year, notably with style-resources-loader set up (not 100% sure if relevant). After running `npm install`, `vue add vuetify`, and `npm run serve`, I'm met with a build failure and many Stylus-related errors:

```
Module build failed (from ./node_modules/stylus-loader/index.js):
ParseError: C:\Development\dashboard\node_modules\vuetify\src\stylus\components\_toolbar.styl:87:12
   83|     align-items: center
   84|     display: flex
   85|     padding: 0 $grid-gutters.xl
   86|
   87|     @media $display-breakpoints.sm-and-down
------------------^
   88|       padding: 0 $grid-gutters.lg
   89|
   90|     .v-btn--icon

expected "indent", got "media"

    at Parser.error (C:\Development\dashboard\node_modules\stylus\lib\parser.js:259:11)
    at Parser.expect (C:\Development\dashboard\node_modules\stylus\lib\parser.js:287:12)
    at Parser.block (C:\Development\dashboard\node_modules\stylus\lib\parser.js:845:12)
    at Parser.selector (C:\Development\dashboard\node_modules\stylus\lib\parser.js:1555:24)
    at Parser.ident (C:\Development\dashboard\node_modules\stylus\lib\parser.js:1446:25)
    at Parser.stmt (C:\Development\dashboard\node_modules\stylus\lib\parser.js:778:26)
    at Parser.statement (C:\Development\dashboard\node_modules\stylus\lib\parser.js:685:21)
    at Parser.parse (C:\Development\dashboard\node_modules\stylus\lib\parser.js:236:25)
    at Renderer.render (C:\Development\dashboard\node_modules\stylus\lib\renderer.js:80:22)
    at C:\Development\dashboard\node_modules\stylus-loader\index.js:167:12
    at tryCatchReject (C:\Development\dashboard\node_modules\when\lib\makePromise.js:840:30)
    at runContinuation1 (C:\Development\dashboard\node_modules\when\lib\makePromise.js:799:4)
    at Fulfilled.when (C:\Development\dashboard\node_modules\when\lib\makePromise.js:590:4)
    at Pending.run (C:\Development\dashboard\node_modules\when\lib\makePromise.js:481:13)
    at Scheduler._drain (C:\Development\dashboard\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (C:\Development\dashboard\node_modules\when\lib\Scheduler.js:27:9)

 @ ./node_modules/vuetify/src/stylus/components/_toolbar.styl 4:14-273 14:3-18:5 15:22-281
 @ ./node_modules/vuetify/lib/components/VToolbar/VToolbar.js
 @ ./node_modules/vuetify/lib/components/VToolbar/index.js
 @ ./node_modules/vuetify/lib/components/index.js
 @ ./node_modules/vuetify/lib/index.js
 @ ./src/App.vue
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://192.168.100.18:8080/sockjs-node (webpack)/hot/dev-server.js
./src/main.ts

 error  in ./node_modules/vuetify/src/stylus/components/_tooltips.styl

Module build failed (from ./node_modules/stylus-loader/index.js):
ParseError: C:\Development\dashboard\node_modules\vuetify\src\stylus\components\_tooltips.styl:50:1
   46|
   47|   @media $display-breakpoints.sm-and-down
   48|     .v-tooltip__content
   49|       padding: 10px 16px
   50|
-------^

expected "indent", got "."

    at Parser.error (C:\Development\dashboard\node_modules\stylus\lib\parser.js:259:11)
    at Parser.expect (C:\Development\dashboard\node_modules\stylus\lib\parser.js:287:12)
    at Parser.block (C:\Development\dashboard\node_modules\stylus\lib\parser.js:845:12)
    at Parser.media (C:\Development\dashboard\node_modules\stylus\lib\parser.js:1151:24)
    at Parser.stmt (C:\Development\dashboard\node_modules\stylus\lib\parser.js:778:26)
    at Parser.statement (C:\Development\dashboard\node_modules\stylus\lib\parser.js:685:21)
    at Parser.parse (C:\Development\dashboard\node_modules\stylus\lib\parser.js:236:25)
    at Renderer.render (C:\Development\dashboard\node_modules\stylus\lib\renderer.js:80:22)
    at C:\Development\dashboard\node_modules\stylus-loader\index.js:167:12
    at tryCatchReject (C:\Development\dashboard\node_modules\when\lib\makePromise.js:840:30)
    at runContinuation1 (C:\Development\dashboard\node_modules\when\lib\makePromise.js:799:4)
    at Fulfilled.when (C:\Development\dashboard\node_modules\when\lib\makePromise.js:590:4)
    at Pending.run (C:\Development\dashboard\node_modules\when\lib\makePromise.js:481:13)
    at Scheduler._drain (C:\Development\dashboard\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (C:\Development\dashboard\node_modules\when\lib\Scheduler.js:27:9)
    at process._tickCallback (internal/process/next_tick.js:176:11)

 @ ./node_modules/vuetify/src/stylus/components/_tooltips.styl 4:14-274 14:3-18:5 15:22-282
 @ ./node_modules/vuetify/lib/components/VTooltip/VTooltip.js
 @ ./node_modules/vuetify/lib/components/VTooltip/index.js
 @ ./node_modules/vuetify/lib/components/index.js
 @ ./node_modules/vuetify/lib/index.js
 @ ./src/App.vue
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://192.168.100.18:8080/sockjs-node (webpack)/hot/dev-server.js
./src/main.ts

 error  in ./node_modules/vuetify/src/stylus/components/_treeview.styl

Module build failed (from ./node_modules/stylus-loader/index.js):
ParseError: C:\Development\dashboard\node_modules\vuetify\src\stylus\components\_treeview.styl:114:1
   110|         animation: progress-circular-rotate
1s linear infinite
   111|
   112|     &__children
   113|       transition: all $treeview-transition
   114|
--------^

expected "indent", got "eos"

    at Parser.error (C:\Development\dashboard\node_modules\stylus\lib\parser.js:259:11)
    at Parser.expect (C:\Development\dashboard\node_modules\stylus\lib\parser.js:287:12)
    at Parser.block (C:\Development\dashboard\node_modules\stylus\lib\parser.js:845:12)
    at Parser.selector (C:\Development\dashboard\node_modules\stylus\lib\parser.js:1555:24)
    at Parser.ident (C:\Development\dashboard\node_modules\stylus\lib\parser.js:1446:25)
    at Parser.stmt (C:\Development\dashboard\node_modules\stylus\lib\parser.js:778:26)
    at Parser.statement (C:\Development\dashboard\node_modules\stylus\lib\parser.js:685:21)
    at Parser.parse (C:\Development\dashboard\node_modules\stylus\lib\parser.js:236:25)
    at Renderer.render (C:\Development\dashboard\node_modules\stylus\lib\renderer.js:80:22)
    at C:\Development\dashboard\node_modules\stylus-loader\index.js:167:12
    at tryCatchReject (C:\Development\dashboard\node_modules\when\lib\makePromise.js:840:30)
    at runContinuation1 (C:\Development\dashboard\node_modules\when\lib\makePromise.js:799:4)
    at Fulfilled.when (C:\Development\dashboard\node_modules\when\lib\makePromise.js:590:4)
    at Pending.run (C:\Development\dashboard\node_modules\when\lib\makePromise.js:481:13)
    at Scheduler._drain (C:\Development\dashboard\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (C:\Development\dashboard\node_modules\when\lib\Scheduler.js:27:9)

 @ ./node_modules/vuetify/src/stylus/components/_treeview.styl 4:14-274 14:3-18:5 15:22-282
 @ ./node_modules/vuetify/lib/components/VTreeview/VTreeview.js
 @ ./node_modules/vuetify/lib/components/VTreeview/index.js
 @ ./node_modules/vuetify/lib/components/index.js
 @ ./node_modules/vuetify/lib/index.js
 @ ./src/App.vue
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://192.168.100.18:8080/sockjs-node (webpack)/hot/dev-server.js
./src/main.ts
```

Replication:
- `git clone -b vuetify-setup https://github.com/salvadornico/dashboard.git`
- `npm install`
- `npm run serve`

Any ideas on what could be going on?

**Comment by johnleider** [comment]
Has something to do with this plugin. https://github.com/nguyenvanduocit/vue-cli-plugin-style-resources-loader . I'm not sure who's at fault here but I'm not sure how to resolve it besides removing that.

**Comment by johnleider** [comment]
This is no longer applicable in the latest version.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
