### ISSUE TITLE
Breaks with typescript project

### ISSUE THREAD

**Issue by divoxx** [vuetifyjs/vue-cli-plugin-vuetify#7]
It tries to replace src/main.js but it doesn't exist since typescript projects will have a src/main.ts

```
$ vue add vuetify

📦  Installing vue-cli-plugin-vuetify...

yarn add v1.6.0
(node:24) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info No lockfile found.




success Saved lockfile.
success Saved 11 new dependencies.
info Direct dependencies
└─ vue-cli-plugin-vuetify@0.1.2
info All dependencies
├─ balanced-match@1.0.0
├─ brace-expansion@1.1.11
├─ concat-map@0.0.1
├─ fs.realpath@1.0.0
├─ glob@7.1.2
├─ inflight@1.0.6
├─ inherits@2.0.3
├─ minimatch@3.0.4
├─ path-is-absolute@1.0.1
├─ rimraf@2.6.2
└─ vue-cli-plugin-vuetify@0.1.2
Done in 0.59s.

✔  Successfully installed plugin: vue-cli-plugin-vuetify
? Allow Vuetify to replace App.vue and HelloWorld.vue? Yes
? Use custom theme? Yes
? Use a-la-carte components? No
🚀  Invoking generator for vue-cli-plugin-vuetify...
yarn install v1.6.0
⠼  Installing additional dependencies...(node:48) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1/4] Resolving packages...
success Saved lockfile.
Done in 1.08s.
📦  Installing additional dependencies...
⠋  Running completion hooks... ERROR  Error: ENOENT: no such file or directory, open '/app/src/main.js'
Error: ENOENT: no such file or directory, open '/app/src/main.js'
    at Object.fs.openSync (fs.js:545:3)
    at Object.fs.readFileSync (fs.js:451:33)
    at api.onCreateComplete (/app/node_modules/vue-cli-plugin-vuetify/generator/index.js:94:24)
    at invoke (/usr/local/lib/node_modules/@vue/cli/lib/invoke.js:123:13)
    at process._tickCallback (internal/process/next_tick.js:178:7)
```

**Comment by jacekkarczmarczyk** [comment]
Seems to be fixed
