### ISSUE TITLE
[Bug Report] 'yarn serve' crashes on syntax error in pug templates

### ISSUE THREAD

**Issue by jn73** [vuetifyjs/vue-cli-plugin-vuetify#80]
### Versions and Environment
**Vuetify:** 1.4.2
**Vue:** 2.5.22
**Browsers:** Chrome 71.0.3578.98
**OS:** Mac OS 10.14.2

### Steps to reproduce
1. checkout git repo https://github.com/jn73/vuetify_pug_bug
2. From root run 'yarn serve'
3. open 'http://localhost:8080/' => the pug template in src/components/HelloWorld.vue is rendered ok
4. edit src/components/HelloWorld.vue (add a single '(' after the div for example) to force a syntax error

### Expected Behavior
Expected an error message in the browser "Failed to compile." and a stack trace.
After fixing the error the page should re-render OK

### Actual Behavior
Nothing happens in the browser. In the terminal the 'yarn serve' displays a stack trace and stops working (efter fixing the pug template it won't recover - yarn needs to be restarted):

10% building 0/1 modules 1 active ...jtt/janne/src/components/HelloWorld.vue(node:21037) UnhandledPromiseRejectionWarning: Error: Pug:4:1
    2| div(
    3| 	| pug
  > 4|
-------^

The end of the string reached with no closing bracket ) found.
    at makeError (/private/tmp/jtt/janne/node_modules/pug-error/index.js:32:13)
    at Lexer.error (/private/tmp/jtt/janne/node_modules/pug-lexer/index.js:59:15)
    at Lexer.bracketExpression (/private/tmp/jtt/janne/node_modules/pug-lexer/index.js:260:14)
    at Lexer.attrs (/private/tmp/jtt/janne/node_modules/pug-lexer/index.js:1270:24)
    at Lexer.callLexerFunction (/private/tmp/jtt/janne/node_modules/pug-lexer/index.js:1456:23)
    at Lexer.advance (/private/tmp/jtt/janne/node_modules/pug-lexer/index.js:1493:15)
    at Lexer.callLexerFunction (/private/tmp/jtt/janne/node_modules/pug-lexer/index.js:1456:23)
    at Lexer.getTokens (/private/tmp/jtt/janne/node_modules/pug-lexer/index.js:1512:12)
    at lex (/private/tmp/jtt/janne/node_modules/pug-lexer/index.js:12:42)
    at Object.lex (/private/tmp/jtt/janne/node_modules/pug/lib/index.js:99:27)
    at Function.loadString [as string] (/private/tmp/jtt/janne/node_modules/pug-load/index.js:44:24)
    at compileBody (/private/tmp/jtt/janne/node_modules/pug/lib/index.js:86:18)
    at Object.exports.compile (/private/tmp/jtt/janne/node_modules/pug/lib/index.js:242:16)
    at Object.module.exports (/private/tmp/jtt/janne/node_modules/vuetify-loader/lib/loader.js:43:42)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:21037) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21037) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Reproduction Link
<a href="https://github.com/jn73/vuetify_pug_bug" target="_blank">https://github.com/jn73/vuetify_pug_bug</a>

**Comment by jn73** [comment]
Just tried reverting vuetify-loader to 1.0.6 in devDependencies and then it works:

"vuetify-loader": "1.0.6"

**Comment by jn73** [comment]
And i guess this belongs in vuetify-loader. Probably a duplicate of https://github.com/vuetifyjs/vuetify-loader/issues/39
